apiVersion: v1
kind: Pod
metadata:
  name: "{{ service-name }}"
  labels:
    app: "{{ app }}"
    env: dev
spec:
  containers:
  - name: locpick-devshell
    image: beatrak/locpick-devshell
    imagePullPolicy: IfNotPresent
    env:
      - name: "LOG_LEVEL"
        value: "{{ log-level }}"
      - name: "SERVICE_NAME"
        value: "{{ service-name }}"
    volumeMounts:
      - mountPath: /root/app
        name: app-volume
      - mountPath: /root/common
        name: common-volume
  - name: locpick-envoy-devshell
    image: beatrak/locpick-envoy
    imagePullPolicy: IfNotPresent
    name: envoy
    ports:
      - containerPort: 50001
        name: locpick-api
        protocol: TCP
      - containerPort: 50011
        name: envoy-admin
        protocol: TCP
  volumes:
    - name: app-volume
      hostPath:
        path: {{ app-volume-path }}
    - name: common-volume
      hostPath:
        path: {{ common-volume-path }}
  nodeSelector:
    kubernetes.io/hostname: {{ hostname }}




