apiVersion: v1
kind: Service
metadata:
    name: "{{ service-name }}"
    labels:
      app: "{{ app }}"
      env: prod
spec:
  ports:
  - name: locpick-api
    port: 50001
    protocol: TCP
    targetPort: 50001
  - name: envoy-admin
    port: 50011
    protocol: TCP
    targetPort: 50011
  clusterIP:  None
  selector:
    app: "{{ app }}"

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ service-name }}"
spec:
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        app: "{{ app }}"
    spec:
      containers:
      - name: locpick-prod
        image: beatrak/locpick
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: "{{ log-level }}"
          - name: "SERVICE_NAME"
            value: "{{ service-name }}"
      - image: beatrak/locpick-envoy
        name: locpick-envoy-prod
        imagePullPolicy: IfNotPresent
        name: envoy
        ports:
          - containerPort: 50001
            name: locpick-api
            protocol: TCP
          - containerPort: 50011
            name: envoy-admin
            protocol: TCP

