apiVersion: v1
kind: Service
metadata:
    name: {{ service-name }}
    labels:
      app: {{ app }}
spec:
  ports:
  - name: stage1-api
    port: 50006
    protocol: TCP
    targetPort: 50006
  - name: envoy-admin
    port: 50011
    protocol: TCP
    targetPort: 50011
  type: ClusterIP
  clusterIP:  None
  selector:
    app: {{ app }}

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ service-name }}
spec:
  selector:
    matchLabels:
      app: {{ app }}
  serviceName: {{ service-name }}
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        app: {{ app }}
    spec:
      containers:
      - name: stage1
        image: beatrak/stage1-devshell
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: {{ log-level }}
          - name: "SERVICE_NAME"
            value: {{ service-name }}
          - name: "CLUSTER"
            value: {{ cluster }}
          - name: "ZONE"
            value: {{ zone }}
        volumeMounts:
          - mountPath: /root/app
            name: app-volume
          - mountPath: /root/common
            name: common-volume
      - name: envoy
        image: beatrak/stage1-envoy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50006
          name: stage1-api
          protocol: TCP
        - containerPort: 50011
          name: envoy-admin
          protocol: TCP
      volumes:
        - name: app-volume
          hostPath:
            path: {{ app-volume-path }}
        - name: common-volume
          hostPath:
            path: {{ common-volume-path }}
      nodeSelector:
        kubernetes.io/hostname: {{ hostname }}




