apiVersion: v1
kind: Service
metadata:
    name: {{ service-name }}
    labels:
      app: {{ app }}
spec:
  ports:
  - name: express-api
    port: 50010
    protocol: TCP
    targetPort: 50010
  - name: react-ui
    port: 50020
    protocol: TCP
    targetPort: 50020
  - name: envoy-admin
    port: 50011
    protocol: TCP
    targetPort: 50011
  type: ClusterIP
  clusterIP:  None
  selector:
    app: {{ app }}

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ service-name }}
spec:
  selector:
    matchLabels:
      app: {{ app }}
  serviceName: {{ service-name }}
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        app: {{ app }}
    spec:
      containers:
      - name: montrer
        image: beatrak/montrer-devshell
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: {{ log-level }}
          - name: "SERVICE_NAME"
            value: {{ service-name }}
        volumeMounts:
          - mountPath: /root/app
            name: app-volume
          - mountPath: /root/common
            name: common-volume
      volumes:
        - name: app-volume
          hostPath:
            path: {{ app-volume-path }}
        - name: common-volume
          hostPath:
            path: {{ common-volume-path }}
      nodeSelector:
        kubernetes.io/hostname: {{ hostname }}




