const LOCPICK_PORT = 50001;
const LOCPICK_DEVSHELL_PORT = 55001;

const BEACON_PORT = 50002;
const BEACON_DEVSHELL_PORT = 55002;

const ELASTIC_PORT = 50003;
const POSTGRESQL_PORT = 50005;

const STAGE1_PORT = 50006;
const STAGE1_DEVSHELL_PORT = 55006;

const ENVOY_ADMIN_PORT = 50011;
const LOCAL_SERVER_PORT = 8080;
const HOST = "127.0.0.1";

module.exports = {
    ELASTIC_PORT: ELASTIC_PORT,
    POSTGRESQL_PORT : POSTGRESQL_PORT,
    LOCPICK_PORT: LOCPICK_PORT,
    LOCPICK_DEVSHELL_PORT: LOCPICK_PORT,
    BEACON_PORT: BEACON_PORT,
    BEACON_DEVSHELL_PORT: BEACON_PORT,
    STAGE1_PORT : STAGE1_PORT,
    STAGE1_DEVSHELL_PORT : STAGE1_DEVSHELL_PORT,
    LOCAL_SERVER_PORT : LOCAL_SERVER_PORT,
    HOST : HOST
};
