const LOCPICK_PORT = 50001;
const BEACON_PORT = 50002;
const ELASTIC_PORT = 50003;

module.exports = {
    LOCPICK_PORT: LOCPICK_PORT,
    BEACON_PORT: BEACON_PORT,
    ELASTIC_PORT: ELASTIC_PORT,
};
